# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8854b712d17b07eb8eb0bd6ffd9fd1a0dffb4d915942362e890fd5afe333852719c9d02cdfa6d912aff2b0178a70643388c71189ab5e2a991a303794e8f59886

test:
  secret_key_base: 4cbfb9c8f46b534fea3aea24802d279099b515c3ef8f79af7f87b957f15f8b9459c540042ca1bc7160c5abf84c4dac24197596ce5fc162ba8eaf6f0ee72afc37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
